CREATE TABLE IF NOT EXISTS `datn-retailing.edw_cleaned.transactions` (
    trn_invc_id               STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Invoice ID\", \"clmn_desc\": \"Invoice ID of the transactions table\"}"),
    trn_line                  INT64 NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Line\", \"clmn_desc\": \"Line of the transactions table\"}"),
    trn_cstmr_id              STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Customer ID\", \"clmn_desc\": \"Customer ID of the transactions table\"}"),
    trn_prd_id                STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Product ID\", \"clmn_desc\": \"Product ID of the transactions table\"}"),
    trn_sz                    STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Size\", \"clmn_desc\": \"Size of the transactions table\"}"),
    trn_cl                    STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Color\", \"clmn_desc\": \"Color of the transactions table\"}"),
    trn_unit_prc              NUMERIC  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Unit Price\", \"clmn_desc\": \"Unit Price of the transactions table\"}"),
    trn_qty                   INT64 NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Quantity\", \"clmn_desc\": \"Quantity of the transactions table\"}"),
    trn_date                  TIMESTAMP NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Date\", \"clmn_desc\": \"Date of the transactions table\"}"),
    trn_dscnt                 NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Discount\", \"clmn_desc\": \"Discount of the transactions table\"}"),
    trn_line_ttl              NUMERIC  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Line Total\", \"clmn_desc\": \"Line Total of the transactions table\"}"),
    trn_str_id                STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store ID\", \"clmn_desc\": \"Store ID of the transactions table\"}"),
    trn_emply_id              STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Employee ID\", \"clmn_desc\": \"Employee ID of the transactions table\"}"),
    trn_crncy                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Currency\", \"clmn_desc\": \"Currency of the transactions table\"}"),
    trn_crncy_sbl             STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Currency Symbol\", \"clmn_desc\": \"Currency Symbol of the transactions table\"}"),
    trn_sku                   STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"SKU\", \"clmn_desc\": \"SKU of the transactions table\"}"),
    trn_type                  STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Transaction Type\", \"clmn_desc\": \"Transaction Type of the transactions table\"}"),
    trn_pymnt_mthd            STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Payment Method\", \"clmn_desc\": \"Payment Method of the transactions table\"}"),
    trn_invc_ttl              NUMERIC  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Invoice Total\", \"clmn_desc\": \"Invoice Total of the transactions table\"}"),
    loaded_batch              STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Loaded Batch\", \"clmn_desc\": \"Unix timestamp of the loaded batch\"}"),
    loaded_part               DATE OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Loaded Part\", \"clmn_desc\": \"Partition date of the batch load\"}"),
    batch_load_ts             TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Batch Load Ts\", \"clmn_desc\": \"Timestamp when batch was loaded\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}")
);