CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_customers` (
    cstmr_surr_key            STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Customer Surrogate Key\", \"clmn_desc\": \"Customer Surrogate Key of the dim_customers table\"}"),
    cstmr_id                  STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Customer ID\", \"clmn_desc\": \"Customer ID of the dim_customers table\"}"),
    cstmr_name                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Name\", \"clmn_desc\": \"Name of the dim_customers table\"}"),
    cstmr_eml                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Email\", \"clmn_desc\": \"Email of the dim_customers table\"}"),
    cstmr_tel                 STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Telephone\", \"clmn_desc\": \"Telephone of the dim_customers table\"}"),
    cstmr_city                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"City\", \"clmn_desc\": \"City of the dim_customers table\"}"),
    cstmr_cntry               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Country\", \"clmn_desc\": \"Country of the dim_customers table\"}"),
    cstmr_gender              STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Gender\", \"clmn_desc\": \"Gender of the dim_customers table\"}"),
    cstmr_brthdy              DATE  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Date of Birth\", \"clmn_desc\": \"Date of Birth of the dim_customers table\"}"),
    cstmr_job_title           STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Job Title\", \"clmn_desc\": \"Job Title of the dim_customers table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);

CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_discounts` (
    dscnt_surr_key            STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Discount Surrogate Key\", \"clmn_desc\": \"Discount Surrogate Key of the dim_discounts table\"}"),
    dscnt_start_date          DATE NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Start Date\", \"clmn_desc\": \"Start Date of the dim_discounts table\"}"),
    dscnt_end_date            DATE  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"End Date\", \"clmn_desc\": \"End Date of the dim_discounts table\"}"),
    dscnt_value               NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Discount\", \"clmn_desc\": \"Discount of the dim_discounts table\"}"),
    dscnt_desc                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description\", \"clmn_desc\": \"Description of the dim_discounts table\"}"),
    dscnt_ctgry               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Category\", \"clmn_desc\": \"Category of the dim_discounts table\"}"),
    dscnt_sub_ctgry           STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Sub Category\", \"clmn_desc\": \"Sub Category of the dim_discounts table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);

CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_employees` (
    emply_surr_key            STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Employee Surrogate Key\", \"clmn_desc\": \"Employee Surrogate Key of the dim_employees table\"}"),
    emply_id                  STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Employee ID\", \"clmn_desc\": \"Employee ID of the dim_employees table\"}"),
    emply_name                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Name\", \"clmn_desc\": \"Name of the dim_employees table\"}"),
    emply_pstn                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Position\", \"clmn_desc\": \"Position of the dim_employees table\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);

CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_products` (
    prd_surr_key              STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Product Surrogate Key\", \"clmn_desc\": \"Product Surrogate Key of the dim_products table\"}"),
    prd_id                    STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Product ID\", \"clmn_desc\": \"Product ID of the dim_products table\"}"),
    prd_ctgry                 STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Category\", \"clmn_desc\": \"Category of the dim_products table\"}"),
    prd_sub_ctgry             STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Sub Category\", \"clmn_desc\": \"Sub Category of the dim_products table\"}"),
    prd_desc_pt               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description PT\", \"clmn_desc\": \"Description PT of the dim_products table\"}"),
    prd_desc_de               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description DE\", \"clmn_desc\": \"Description DE of the dim_products table\"}"),
    prd_desc_fr               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description FR\", \"clmn_desc\": \"Description FR of the dim_products table\"}"),
    prd_desc_es               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description ES\", \"clmn_desc\": \"Description ES of the dim_products table\"}"),
    prd_desc_en               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description EN\", \"clmn_desc\": \"Description EN of the dim_products table\"}"),
    prd_desc_zh               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description ZH\", \"clmn_desc\": \"Description ZH of the dim_products table\"}"),
    prd_color                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Color\", \"clmn_desc\": \"Color of the dim_products table\"}"),
    prd_sizes                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Sizes\", \"clmn_desc\": \"Sizes of the dim_products table\"}"),
    prd_cost                  NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Production Cost\", \"clmn_desc\": \"Production Cost of the dim_products table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);

CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_stores` (
    str_surr_key              STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Surrogate Key\", \"clmn_desc\": \"Store Surrogate Key of the dim_stores table\"}"),
    str_id                    STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store ID\", \"clmn_desc\": \"Store ID of the dim_stores table\"}"),
    str_cntry                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Country\", \"clmn_desc\": \"Country of the dim_stores table\"}"),
    str_city                  STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"City\", \"clmn_desc\": \"City of the dim_stores table\"}"),
    str_name                  STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Name\", \"clmn_desc\": \"Store Name of the dim_stores table\"}"),
    str_emply_num             INT64  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Number of Employees\", \"clmn_desc\": \"Number of Employees of the dim_stores table\"}"),
    str_zip_cd                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"ZIP Code\", \"clmn_desc\": \"ZIP Code of the dim_stores table\"}"),
    str_sz                    STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Size\", \"clmn_desc\": \"Store Size of the dim_stores table\"}"),
    str_lat                   NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Latitude\", \"clmn_desc\": \"Latitude of the dim_stores table\"}"),
    str_lon                   NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Longitude\", \"clmn_desc\": \"Longitude of the dim_stores table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);

CREATE TABLE IF NOT EXISTS `datn-retailing.edw.fact_transactions` (
    trn_id                    STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Transaction ID\", \"clmn_desc\": \"Transaction ID of the fact_transactions table\"}"),
    trn_hr                    INT64 NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Transaction Hour\", \"clmn_desc\": \"Transaction Hour of the fact_transactions table\"}"),
    trn_dt_key                STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Date Key\", \"clmn_desc\": \"Date Key of the fact_transactions table\"}"),
    trn_cstmr_key             STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Customer Key\", \"clmn_desc\": \"Customer Key of the fact_transactions table\"}"),
    trn_prd_key               STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Product Key\", \"clmn_desc\": \"Product Key of the fact_transactions table\"}"),
    trn_str_key               STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Key\", \"clmn_desc\": \"Store Key of the fact_transactions table\"}"),
    trn_emply_key             STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Employee Key\", \"clmn_desc\": \"Employee Key of the fact_transactions table\"}"),
    trn_dscnt_key             STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Discount Key\", \"clmn_desc\": \"Discount Key of the fact_transactions table\"}"),
    trn_sale_qty              INT64 NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Sale Quantity\", \"clmn_desc\": \"Sale Quantity of the fact_transactions table\"}"),
    trn_reg_unit_prc          NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Regular Unit Price\", \"clmn_desc\": \"Regular Unit Price of the fact_transactions table\"}"),
    trn_dscnt_unit_prc        NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Discount Unit Price \", \"clmn_desc\": \"Discount Unit Price  of the fact_transactions table\"}"),
    trn_net_unit_prc          NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Net Unit Price\", \"clmn_desc\": \"Net Unit Price of the fact_transactions table\"}"),
    trn_ext_sale_dol          NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Extended Sales Dollar Amount\", \"clmn_desc\": \"Extended Sales Dollar Amount of the fact_transactions table\"}"),
    trn_ext_dscnt_dol         NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Extended Discount Dollar Amount\", \"clmn_desc\": \"Extended Discount Dollar Amount of the fact_transactions table\"}"),
    trn_line_ttl              NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Line Total\", \"clmn_desc\": \"Line Total of the fact_transactions table\"}"),
    trn_sz                    STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Size\", \"clmn_desc\": \"Size of the fact_transactions table\"}"),
    trn_cl                    STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Color\", \"clmn_desc\": \"Color of the fact_transactions table\"}"),
    trn_crncy                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Currency\", \"clmn_desc\": \"Currency of the fact_transactions table\"}"),
    trn_crncy_sbl             STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Currency Symbol\", \"clmn_desc\": \"Currency Symbol of the fact_transactions table\"}"),
    trn_type                  STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Transaction Type\", \"clmn_desc\": \"Transaction Type of the fact_transactions table\"}"),
    trn_pymnt_mthd            STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Payment Method\", \"clmn_desc\": \"Payment Method of the fact_transactions table\"}"),
    trn_sku                   STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"SKU\", \"clmn_desc\": \"SKU of the fact_transactions table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);