CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_products` (
    prd_surr_key              STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Product Surrogate Key\", \"clmn_desc\": \"Product Surrogate Key of the dim_products table\"}"),
    prd_id                    STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Product ID\", \"clmn_desc\": \"Product ID of the dim_products table\"}"),
    prd_ctgry                 STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Category\", \"clmn_desc\": \"Category of the dim_products table\"}"),
    prd_sub_ctgry             STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Sub Category\", \"clmn_desc\": \"Sub Category of the dim_products table\"}"),
    prd_desc_pt               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description PT\", \"clmn_desc\": \"Description PT of the dim_products table\"}"),
    prd_desc_de               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description DE\", \"clmn_desc\": \"Description DE of the dim_products table\"}"),
    prd_desc_fr               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description FR\", \"clmn_desc\": \"Description FR of the dim_products table\"}"),
    prd_desc_es               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description ES\", \"clmn_desc\": \"Description ES of the dim_products table\"}"),
    prd_desc_en               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description EN\", \"clmn_desc\": \"Description EN of the dim_products table\"}"),
    prd_desc_zh               STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Description ZH\", \"clmn_desc\": \"Description ZH of the dim_products table\"}"),
    prd_color                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Color\", \"clmn_desc\": \"Color of the dim_products table\"}"),
    prd_sizes                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Sizes\", \"clmn_desc\": \"Sizes of the dim_products table\"}"),
    prd_cost                  NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Production Cost\", \"clmn_desc\": \"Production Cost of the dim_products table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);