CREATE TABLE IF NOT EXISTS `datn-retailing.edw.dim_stores` (
    str_surr_key              STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Surrogate Key\", \"clmn_desc\": \"Store Surrogate Key of the dim_stores table\"}"),
    str_id                    STRING NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store ID\", \"clmn_desc\": \"Store ID of the dim_stores table\"}"),
    str_cntry                 STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Country\", \"clmn_desc\": \"Country of the dim_stores table\"}"),
    str_city                  STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"City\", \"clmn_desc\": \"City of the dim_stores table\"}"),
    str_name                  STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Name\", \"clmn_desc\": \"Store Name of the dim_stores table\"}"),
    str_emply_num             INT64  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Number of Employees\", \"clmn_desc\": \"Number of Employees of the dim_stores table\"}"),
    str_zip_cd                STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"ZIP Code\", \"clmn_desc\": \"ZIP Code of the dim_stores table\"}"),
    str_sz                    STRING  OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Store Size\", \"clmn_desc\": \"Store Size of the dim_stores table\"}"),
    str_lat                   NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Latitude\", \"clmn_desc\": \"Latitude of the dim_stores table\"}"),
    str_lon                   NUMERIC NOT NULL OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Longitude\", \"clmn_desc\": \"Longitude of the dim_stores table\"}"),
    effective_start_date      TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective Start Date\", \"clmn_desc\": \"Effective start date (timestamp) of the record\"}"),
    effective_end_date        TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Effective End Date\", \"clmn_desc\": \"Effective end date (timestamp) of the record\"}"),
    flag_active               STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Flag Active\", \"clmn_desc\": \"Flag to indicate if the record is active\"}"),
    create_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Date\", \"clmn_desc\": \"Timestamp when record was created in cleaned layer\"}"),
    create_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Id\", \"clmn_desc\": \"Airflow task ID that created this record\"}"),
    create_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Create Task Run Id\", \"clmn_desc\": \"Airflow run ID that created this record\"}"),
    update_date               TIMESTAMP OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Date\", \"clmn_desc\": \"Timestamp when record was updated in cleaned layer\"}"),
    update_task_id            STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Id\", \"clmn_desc\": \"Airflow task ID that updated this record\"}"),
    update_task_run_id        STRING OPTIONS(description="{\"clmn_lgcl_name_eng\": \"Update Task Run Id\", \"clmn_desc\": \"Airflow run ID that updated this record\"}")
);